# Generated by Django 2.2.4 on 2019-08-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.CharField(max_length=3)),
                ('i', models.CharField(max_length=3)),
                ('n', models.CharField(max_length=3)),
                ('g', models.CharField(max_length=3)),
                ('o', models.CharField(max_length=3)),
            ],
        ),
    ]
