# Generated by Django 2.2.4 on 2019-08-13 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='card',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='play.Card'),
            preserve_default=False,
        ),
    ]
