# Generated by Django 2.2.4 on 2019-08-13 16:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_row_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=5), size=5)),
            ],
        ),
        migrations.AlterField(
            model_name='row',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='play.Card'),
        ),
    ]
