# Generated by Django 2.2.4 on 2019-08-13 17:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_auto_20190813_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bingoboard',
            name='board',
        ),
        migrations.RemoveField(
            model_name='row',
            name='card',
        ),
        migrations.AddField(
            model_name='bingoboard',
            name='b',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=["01","04","07","10","13"], size=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bingoboard',
            name='g',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=["16","19","22","25","28"], size=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bingoboard',
            name='i',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=["31","34","37","40","43"], size=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bingoboard',
            name='n',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=["46","49","52","55","57"], size=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bingoboard',
            name='o',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=["61","64","67","70","73"], size=5),
            preserve_default=False,
        ),
    ]
