# Generated by Django 2.2.4 on 2019-08-13 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_auto_20190813_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='play.Card'),
            preserve_default=False,
        ),
    ]
