# Generated by Django 2.2.4 on 2019-08-13 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_row_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rows',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=[1, 16, 31, 46, 61], size=5),
            preserve_default=False,
        ),
    ]
