# Generated by Django 2.2.4 on 2019-08-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_card_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='rows',
        ),
    ]
